//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSDistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dijkstra
    {
        public long Dijkstra編號 { get; set; }
        public long 起站編號 { get; set; }
        public long 迄站編號 { get; set; }
        public Nullable<decimal> 最短距離 { get; set; }
        public Nullable<int> 最短時間 { get; set; }
        public Nullable<int> 最少票價 { get; set; }
    }
}
