//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSDistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class 線路
    {
        public string 線路編號 { get; set; }
        public string 中文名稱 { get; set; }
        public string 俄文名稱 { get; set; }
        public string 英文名稱 { get; set; }
        public Nullable<int> 開通年份 { get; set; }
        public Nullable<int> 擴建年份 { get; set; }
        public Nullable<decimal> 全長 { get; set; }
        public Nullable<int> 站數 { get; set; }
        public Nullable<decimal> 平均長度 { get; set; }
        public byte[] 標誌 { get; set; }
    }
}
